from atm.utils.uploader.piggo_upload import piggo_upload
from atm.utils.uploader.hdsky_upload import hdsky_upload
from atm.utils.uploader.audience_upload import audience_upload
from atm.utils.uploader.ssd_upload import ssd_upload
from atm.utils.uploader.pter_upload import pter_upload
from atm.utils.uploader.hhclub_upload import hhclub_upload
from atm.utils.uploader.hdpt_upload import hdpt_upload
from atm.utils.uploader.wintersakura_upload import wintersakura_upload
from atm.utils.uploader.carpt_upload import carpt_upload
from atm.utils.uploader.hdfans_upload import hdfans_upload
from atm.utils.uploader.hares_upload import hares_upload
from atm.utils.uploader.zmpt_upload import zmpt_upload
from atm.utils.uploader.hdvideo_upload import hdvideo_upload
from atm.utils.uploader.redleaves_upload import redleaves_upload
from atm.utils.uploader.mteam_upload import mteam_upload
from atm.utils.uploader.zhuque_upload import zhuque_upload
from atm.utils.uploader.dajiao_upload import dajiao_upload
from atm.utils.uploader.pandapt_upload import pandapt_upload
from atm.utils.uploader.rousi_upload import rousi_upload
from atm.utils.uploader.ptlsp_upload import ptlsp_upload
from atm.utils.uploader.okpt_upload import okpt_upload
from atm.utils.uploader.yiptba_upload import yiptba_upload
from atm.utils.uploader.mangguo_upload import mangguo_upload
from atm.utils.uploader.wuerpt_upload import wuerpt_upload
from atm.utils.uploader.btschool_upload import btschool_upload
from atm.utils.uploader.freefarm_upload import freefarm_upload
from atm.utils.uploader.discfan_upload import discfan_upload
from atm.utils.uploader.dragonhd_upload import dragonhd_upload
from atm.utils.uploader.cyanbug_upload import cyanbug_upload
from atm.utils.uploader.hdarea_upload import hdarea_upload
from atm.utils.uploader.hdhome_upload import hdhome_upload
from atm.utils.uploader.hddolby_upload import hddolby_upload
from atm.utils.uploader.hdmayi_upload import hdmayi_upload
from atm.utils.uploader.hdtime_upload import hdtime_upload
from atm.utils.uploader.hdu_upload import hdu_upload
from atm.utils.uploader.hdzone_upload import hdzone_upload
from atm.utils.uploader.hitpt_upload import hitpt_upload
from atm.utils.uploader.hudbt_upload import hudbt_upload
from atm.utils.uploader.haidan_upload import haidan_upload
from atm.utils.uploader.icc_upload import icc_upload
from atm.utils.uploader.itzmx_upload import itzmx_upload
from atm.utils.uploader.joyhd_upload import joyhd_upload
from atm.utils.uploader.nanyang_upload import nanyang_upload
from atm.utils.uploader.oshen_upload import oshen_upload
from atm.utils.uploader.pttime_upload import pttime_upload
from atm.utils.uploader.pthome_upload import pthome_upload
from atm.utils.uploader.ptsbao_upload import ptsbao_upload
from atm.utils.uploader.soulvoice_upload import soulvoice_upload
from atm.utils.uploader.ubits_upload import ubits_upload
from atm.utils.uploader.ptchina_upload import ptchina_upload
from atm.utils.uploader.ydy_upload import ydy_upload
from atm.utils.uploader.gtk_upload import gtk_upload
from atm.utils.uploader.ptcafe_upload import ptcafe_upload
from atm.utils.uploader.kufei_upload import kufei_upload
from atm.utils.uploader.tccf_upload import tccf_upload
from atm.utils.uploader.hdpost_upload import hdpost_upload
from atm.utils.uploader.ilolicon_upload import ilolicon_upload

def auto_upload(siteitem,file,record_path,qbinfo,basic,hashlist):
    return eval(siteitem.sitename+'_upload(siteitem,file,record_path,qbinfo,basic,hashlist)')